name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --check

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: Dry run publish
        run: cargo publish --dry-run

  publish:
    runs-on: ubuntu-latest
    needs: [ build, lint ]
    if: github.ref == 'refs/heads/master'
    steps:
        - uses: actions/checkout@v3
        - run: cargo publish --token $CARGO_REGISTRY_TOKEN
          env:
            CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
